/**
 * Technical information: what in this simulation is calculated, what is a design value, what
 * is an engineering estimate and what is only drawn — plus the models, their assumptions and
 * limits, and the sources. Opened from the header's (i).
 */
import { useEffect, useRef } from 'react';
import { PROVENANCE_HELP, PROVENANCE_LABEL, type Provenance } from '../spec/provenance';
import { useApp } from '../state/store';
import { Dot } from './kit';

const MODELS: { title: string; body: string }[] = [
  { title: 'Actuators', body: 'DC-equivalent permanent-magnet motor: τm = Kt·I (Kt falling 12 % towards peak current), V = I·R(T) + Kt·ω, R(T) = R20·(1 + 0.00393·(T − 20)). Reducer: τout = τm·N·η driving, τm·N/η_back when back-driven, plus Coulomb and viscous friction. Reflected inertia N²·J_rotor. Two-node thermal network (winding, housing); continuous ratings are derived from it, not typed in. Drives derate current from 120 °C and stop at 140 °C.' },
  { title: 'Battery', body: '14S9P 21700 cells: open-circuit voltage from a typical NMC curve, internal resistance rising in the cold and at low charge, terminal voltage V = OCV − I·R, heat I²R. Runtime = usable energy / average power. Pre-charge, contactors and fuse are sized, not simulated electrically.' },
  { title: 'Mass and balance', body: 'A component-level mass budget (every actuator, board, cell and tube) gives the centre of mass for any pose. Support polygon = convex hull of the sole corners touching the floor. Zero-moment point from whole-body moment balance; capture point ξ = c + ċ/ω with ω = √(g/z).' },
  { title: 'Dynamics', body: 'Joint torques by Newton–Euler over each joint\'s distal subtree (segment masses and accelerations, ground reactions shared between the feet, payload at the palms) plus the rotor\'s reflected inertia. Accelerations from the motion itself (the gait at 100 Hz, other motions from successive frames, filtered).' },
  { title: 'Walking', body: 'Footstep plan, ZMP reference and preview control of the cart–table model (Kajita 2003); swing feet on quintic paths; heel strike and toe-off as rotations about the sole edges; COM height from leg reach. The planned motion is assumed to be tracked exactly.' },
  { title: 'Push recovery', body: 'Linear inverted pendulum with divergent-component-of-motion feedback; the centre of pressure is clamped to the support polygon (ankle strategy), a hip-torque burst shifts the centroidal moment pivot (hip strategy), and a step is placed on the predicted capture point within step length and time limits.' },
  { title: 'Kinematics', body: 'Forward kinematics on the 29-joint tree. Legs: closed-form inverse kinematics. Arms: damped least squares on 7 joints with a posture term in the null space; orientation optional.' },
  { title: 'Grasping', body: 'Two-contact friction grasp: holds while m·(g + a) ≤ 2μN. Partial slip at the contact edge above ~85 % of μ produces a vibration signal; the controller re-estimates μ from shear/normal and raises the grip at the finger actuators\' rate, capped below crush force.' },
  { title: 'Structure', body: 'Limb tubes checked in bending, σ = M·c / I, against a design moment of three times the joint\'s peak torque. A first sizing check: no fatigue, buckling, joints or stress concentrations.' },
  { title: 'Sensing', body: 'Stereo depth error σz = z²·σd / (f·B). IMU with bias and noise, fused by a complementary filter. These appear as numbers in the interface; the camera view is rendered, not simulated as an image sensor.' },
];

const VISUAL: string[] = [
  'The motor inside an opened actuator turns at one eighth of its real speed so it can be followed; the readouts are real-time.',
  'Flow dashes along the cables show direction and relative power, not current density.',
  'The thermal view spreads each heat source\'s temperature over nearby surfaces with a fixed falloff: the source temperatures are calculated, the spread is not.',
  'Force arrows are scaled for legibility (1 m ≈ 1500 N at the feet).',
  'Heating in the thermal demonstrations is sped up (the factor is shown).',
  'The cart driving in, covers lifting off and parts separating are choreography.',
];

const LIMITS: string[] = [
  'No full rigid-body contact simulation: motions are generated by planners and tracked exactly; the dynamics are computed from them (inverse dynamics), not integrated forward. Falls stop at the point of failure.',
  'Motors: no field weakening, cogging, saturation of the magnetic circuit beyond the Kt droop, or inverter switching losses beyond a constant efficiency.',
  'Reducers: constant efficiencies by type and ratio; no backlash or compliance in the walking model (the joint lab includes stiction).',
  'Thermal: two lumped nodes per actuator; no heat flow between actuators; constant ambient.',
  'Grasping: two-contact pinch model; no object rotation in the hand, no finger compliance.',
  'Engineering estimates (motor constants, thermal resistances, friction, sensor noise, electronics power) are chosen within published ranges for components of this class; they are not measurements of a specific product.',
];

const REFS: string[] = [
  'Kajita et al., Biped walking pattern generation by using preview control of ZMP, ICRA 2003',
  'Kajita, Hirukawa, Harada, Yokoi, Introduction to Humanoid Robotics, Springer 2014',
  'Pratt, Carff, Drakunov, Goswami, Capture Point: a step toward humanoid push recovery, Humanoids 2006',
  'Englsberger, Ott, Albu-Schäffer, Three-dimensional bipedal walking control based on DCM, IEEE T-RO 2015',
  'Vukobratović & Borovac, Zero-moment point — thirty five years of its life, IJHR 2004',
  'Featherstone, Rigid Body Dynamics Algorithms, Springer 2008',
  'Wensing et al., Proprioceptive actuator design in the MIT Cheetah, IEEE T-RO 2017; Katz, MIT thesis 2018',
  'Seok et al., Design principles for energy-efficient legged locomotion, IEEE/ASME T-Mech 2015',
  'Harmonic Drive CSF/CSG catalogue; Nabtesco RV catalogue (reducer efficiencies and ratios)',
  'Molicel P45B and Samsung 50S 21700 cell datasheets; IEC 62368-1 (ES1, 60 V DC)',
  'Collins, Ruina, Tedrake, Wisse, Efficient bipedal robots based on passive-dynamic walkers, Science 2005 (cost of transport)',
  'Romano et al., Human-inspired robotic grasp control with tactile sensing, IEEE T-RO 2011; Johansson & Westling (grip–load coupling)',
  'Winter, Biomechanics and Motor Control of Human Movement; de Leva 1996 (segment parameters); Perry, Gait Analysis',
  'Public specifications of adult-size electric humanoids, used only as ranges (see docs/ENGINEERING.md)',
];

export function TechInfo() {
  const set = useApp((s) => s.set);
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    ref.current?.focus();
    const key = (e: KeyboardEvent) => e.key === 'Escape' && set({ info: false });
    window.addEventListener('keydown', key);
    return () => window.removeEventListener('keydown', key);
  }, [set]);
  const kinds: Provenance[] = ['calculated', 'design', 'estimate', 'visual'];
  return (
    <div className="info pe" role="dialog" aria-modal="true" aria-labelledby="info-title" onClick={(e) => e.target === e.currentTarget && set({ info: false })}>
      <div className="info__panel panel" ref={ref} tabIndex={-1}>
        <button className="ibtn info__close" onClick={() => set({ info: false })} aria-label="Close">
          <svg width="14" height="14" viewBox="0 0 16 16" aria-hidden>
            <path d="M3.6 2.5 8 6.9l4.4-4.4 1.1 1.1L9.1 8l4.4 4.4-1.1 1.1L8 9.1l-4.4 4.4-1.1-1.1L6.9 8 2.5 3.6z" fill="currentColor" />
          </svg>
        </button>
        <p className="eyebrow">Technical information</p>
        <h2 className="side__title" id="info-title">
          How FO-H1 is simulated
        </h2>
        <p className="side__lede">FO-H1 is an original design made for this simulation, not a copy of any robot. Its numbers come from one specification and a set of reduced-order engineering models, the kind used to size real machines. Every value in the interface is marked:</p>
        <div className="info__kinds">
          {kinds.map((k) => (
            <div key={k} className="info__kind">
              <Dot kind={k} />
              <b>{PROVENANCE_LABEL[k]}</b>
              <span>{PROVENANCE_HELP[k]}</span>
            </div>
          ))}
        </div>
        <h3 className="report__title">What is calculated</h3>
        <dl className="info__models">
          {MODELS.map((m) => (
            <div key={m.title}>
              <dt>{m.title}</dt>
              <dd>{m.body}</dd>
            </div>
          ))}
        </dl>
        <h3 className="report__title">Visual approximations</h3>
        <ul className="notes">
          {VISUAL.map((x) => (
            <li key={x}>{x}</li>
          ))}
        </ul>
        <h3 className="report__title">Limitations</h3>
        <ul className="notes">
          {LIMITS.map((x) => (
            <li key={x}>{x}</li>
          ))}
        </ul>
        <h3 className="report__title">Sources</h3>
        <ol className="notes info__refs">
          {REFS.map((x) => (
            <li key={x}>{x}</li>
          ))}
        </ol>
        <p className="note-small">The full derivations, parameter tables and reference list are in the project's ENGINEERING.md.</p>
      </div>
    </div>
  );
}
